      subroutine readctrl() 
      use prec, only : short
      use paramlist
      use constant, only : ha2ev

      implicit none
      integer(short) i

      open(4,file='axas.in',status='old')
!---------read the control file  
!
!!----comment
!!    n:       number of excited atoms
!!    t_ifile: prefix of input files of spectrum (e.g., if aaa-at1.spectrum is 
!!              generated by cp2k, then 'aaa-at' will be used for t_ifile)
!!    t_ofile: prefix of output file 
!!    sigma_min: minimum of sigma (i.e.,$\sigma_\mathrm{min}$ (in eV)
!!    sigma_max: maximum of sigma (i.e.,$\sigma_\mathrm{max}$ (in eV) 
!!    ne: number of points in the energy axis 
!!    egs: total energy of ground state (in Hartree) 
!!    iatom(i): index of excited atom
!!    eexcit(i): total energy of excited state in the DSCF calculations
!!               for the excited atom i  (in Hartree)
!!    eb(i): the ionization energy (or binding energy) in the TP_HH
!!             calculations for the excited atom i (in Hartree, positive) 
!!    lsum: logical variable, whether sum up the spectra of the selected atoms
!!    nsatom: number of selected atoms
!!    ebmin: the starting energy point of broden XAS data 
!!    isatom: the index of selected atoms
      read(4,*) natom
      read(4,*) t_ifile, t_ofile
      read(4,*) sigma_min, sigma_max
      read(4,*) ne, egs 

      allocate(iatom(natom))
      allocate(eexcit(natom))
      allocate(eb(natom))

!--- convert Hatree to eV
      egs = egs * ha2ev

      do i = 1, natom
         read(4,*) iatom(i), eexcit(i), eb(i)
!--- convert Hatree to eV
          eb(i) = eb(i) * ha2ev 
          eexcit(i) = eexcit(i) * ha2ev 
          write(*,*) 'Eb(1s) of atom ', iatom(i), ':', eb(i), 'eV' 
      end do

      read(4,*) lsum
      if (lsum) then
          read(4,*) nsatom, ebmin
          allocate(isatom(nsatom))
          allocate(isrepeat(nsatom))
          read(4,*) (isatom(i), i= 1, nsatom) 
          read(4,*) (isrepeat(i), i= 1, nsatom) 
          write(*,*) 'The spectra of atoms ', (isatom(i), i=1, nsatom), &
                      'will be summed up!'
      end if

      close(4)
      return
      end subroutine readctrl 
